apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-playbooks-test
  namespace: flux-system
spec:
  interval: 1m
  ref:
    branch: main
  timeout: 60s
  url: https://github.com/flanksource/flux-playbooks-test.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-playbooks-test
  namespace: flux-system
spec:
  interval: 1m
  path: ./
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-playbooks-test
